### ISSUE TITLE
Fail to launch the app after first run

### ISSUE THREAD

**Issue by tre8154** [leandroarndt/msfs_livery_tools#20]
Hi, I just download the lastest build with the exe and install it on my computer. It was success at the first luanch. However, after I close te windows and re-open the bat file it won't start aymore. The command window will fash out anyway. I saw there's few report regard same issue on the flightsim.to aswell.

Here's (below) what I got after I insert a pause script by the end of the bat file:
======================================================================
C:\Program Files (x86)\MSFS Livery Tools>pushd C:\Program Files (x86)\MSFS Livery Tools\

C:\Program Files (x86)\MSFS Livery Tools>python.exe livery_tools.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\MSFS Livery Tools\livery_tools.py", line 19, in <module>
    app = main.MainWindow()
          ^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\gui\main.py", line 135, in __init__
    self.app_settings = AppSettings()
                        ^^^^^^^^^^^^^
  File "C:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\settings\app_settings.py", line 98, in __init__
    __class__._config_parser.read(self.file, encoding='utf-8')
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 50: invalid start byte

C:\Program Files (x86)\MSFS Livery Tools>popd

C:\Program Files (x86)\MSFS Livery Tools>pause

**Comment by leandroarndt** [comment]
Much thanks for opening this issue. I'll take a look ASAP.

**Comment by leandroarndt** [comment]
I've been able to force the error, but not reproduce the steps prior to it, since it depends on system language settings. I'll need your help testing the possible solution. Could you please:

1. Delete the file _.msfs_livery_tools.cfg_ at your _%userprofile%_ folder.
2. Change the final part of the file _C:\Program Files (x86)\MSFS Livery Tools\msfs_livery_tools\settings\app_settings.py_ so that it reads like this (that is, add `, encoding='utf-8'` to the middle line):

```
    def save(self, *args, **kwargs):
        with open(self.file, 'w', encoding='utf-8') as f:
            __class__._config_parser.write(f, *args, **kwargs)

```
3. Rerun the tool?
